# Generated by Django 3.1.1 on 2020-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prof',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Профиль'),
        ),
    ]
