# Generated by Django 3.1.1 on 2020-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0002_order_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Информация'),
        ),
    ]
