# Generated by Django 3.1.1 on 2020-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0003_auto_20200928_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
