# Generated by Django 3.1.1 on 2020-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0004_order_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ord_aut_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.IntegerField(default='', editable=False, null=True, verbose_name='Номер заказа')),
                ('tel_id', models.CharField(blank=True, editable=False, max_length=45, null=True, verbose_name='Автор')),
                ('price', models.CharField(blank=True, max_length=80, null=True, verbose_name='Цена')),
                ('com', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарий')),
                ('auth_username', models.CharField(blank=True, max_length=80, null=True, verbose_name='Username')),
            ],
        ),
    ]
