# Generated by Django 3.1.1 on 2020-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0011_auto_20201001_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ord_auth_price',
            fields=[
                ('ord_id', models.IntegerField(verbose_name = 'Номер заказа', null=True, editable=False, unique=False)),
                ('tel_id', models.CharField(verbose_name ="Автор", max_length=45, blank=True, null=True, editable=False)),
                ('price', models.CharField(verbose_name ="Цена", max_length=80, blank=True, null=True)),
                ('com', models.CharField(verbose_name ="Комментарий", max_length=2000, blank=True, null=True)),
                ('auth_username', models.CharField(verbose_name ="Username", max_length=80, blank=True, null=True)),
                ('unique', models.IntegerField(verbose_name ='Номер заказа', null=False, editable=False, unique=False, primary_key=True, default=1)),
            ],
        ),
    ]
