# Generated by Django 3.1.1 on 2020-10-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0012_auto_20201001_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceo',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Оплата'),
        ),
    ]
