# Generated by Django 3.1.1 on 2020-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0015_auto_20201005_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeo',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='authors Username'),
        ),
    ]
