# Generated by Django 3.1.1 on 2020-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0018_auto_20201012_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceledo',
            name='why',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Причина'),
        ),
    ]
