# Generated by Django 3.1.1 on 2020-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0019_auto_20201012_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeo',
            name='links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='canceledo',
            name='links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='doneo',
            name='author_links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='doneo',
            name='links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='priceo',
            name='links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='waito',
            name='author_links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
        migrations.AlterField(
            model_name='waito',
            name='links',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ссылки на документы'),
        ),
    ]
