# Generated by Django 3.1.1 on 2020-10-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0020_auto_20201021_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPO',
            fields=[
                ('ord_id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('username', models.CharField(blank=True, max_length=300, null=True, verbose_name='username Авторa')),
                ('cost', models.CharField(blank=True, max_length=45, null=True, verbose_name='стоимость работы автора')),
                ('card_num', models.CharField(blank=True, max_length=45, null=True, verbose_name='Номер карты')),
                ('fio', models.CharField(blank=True, max_length=45, null=True, verbose_name='ФИО автора')),
            ],
        ),
    ]
