# Generated by Django 3.1.1 on 2020-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0021_auto_20201023_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_pri',
            fields=[
                ('ord_id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('tel_id', models.CharField(blank=True, editable=False, max_length=45, null=True, verbose_name='Автор')),
                ('price', models.CharField(blank=True, max_length=80, null=True, verbose_name='Цена автора')),
                ('com', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарий')),
                ('auth_username', models.CharField(blank=True, max_length=80, null=True, verbose_name='Username')),
                ('customer_pr', models.CharField(blank=True, max_length=80, null=True, verbose_name='Цена для заказчика')),
                ('customer_username', models.CharField(blank=True, max_length=80, null=True, verbose_name='Username заказчика')),
            ],
        ),
    ]
