# Generated by Django 3.1.1 on 2020-12-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0023_auto_20201207_0939'),
    ]

    operations = [

    ]
