# Generated by Django 3.1.1 on 2020-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0024_auto_20201207_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='pays',
            fields=[
                ('ord_id', models.CharField(blank=True, editable=False, max_length=45, primary_key=True, serialize=False, verbose_name='ord_id')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
