# Generated by Django 3.1.1 on 2020-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0025_auto_20201210_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='ord_id',
            field=models.CharField(blank=True, max_length=45, primary_key=True, serialize=False, verbose_name='ord_id'),
        ),
    ]
